### ISSUE TITLE
Status Update for one-time jobs

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/job-status-listener#1]
Finished one-time jobs should get a "FINISHED" status rather than "WAITING" since there are no more process executions. This concerns the following lines:
https://github.com/WaCoDiS/job-status-listener/blob/6e32371f2ad6d9ff67757c49bb91bd89311a7c5a/src/main/java/de/wacodis/jobstatuslistener/messaging/listener/ToolExecutionFinishedHandler.java#L51-L58

**Comment by arnevogt** [comment]
issue is fixed with:
[job status listener 1.0.1 release](https://github.com/WaCoDiS/job-status-listener/releases/tag/v1.0.1)
[core engine 1.2.1 release](https://github.com/WaCoDiS/core-engine/releases/tag/v1.2.1)
[job defintion api 1.2.0 release](https://github.com/WaCoDiS/job-definition-api/releases/tag/v1.2.0)  
  
It is nessecary to deploy the named release versions (or later) of job status listener, core engine and job definition api together.
